:queues:
  - aimitsu_scraping
  - base_scraping
  - aimitsusaas_scraping
  - keyword_scraping
  - rekaizen_scraping
:limits:
  aimitsu_scraping: 1
  base_scraping: 1
  aimitsusaas_scraping: 1
  keyword_scraping: 1
  rekaizen_scraping: 1