:queues:
  - aimitsu_scraping
  - baseconnect_scraping
  - keyword_scraping
  - rekaizen_scraping
  - aimitsu_saas_scraping
:limits:
  aimitsu_scraping: 1
  baseconnect_scraping: 1
  keyword_scraping: 1
  rekaizen_scraping: 1
  aimitsu_saas_scraping: 1